# Generated by Django 4.1.9 on 2023-06-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient_Details",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(default=0, max_length=20)),
                ("place", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("doctor", models.CharField(max_length=100)),
                ("height", models.FloatField(default=0, max_length=100)),
                ("weight", models.FloatField(default=0, max_length=100)),
                ("date", models.DateField(auto_now=True)),
                ("ap_date", models.DateTimeField()),
            ],
        ),
    ]
