# Generated by Django 4.1.9 on 2023-06-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_patient_details"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient_details", name="ap_date",),
        migrations.RemoveField(model_name="patient_details", name="date",),
    ]
