# Generated by Django 4.1.9 on 2023-07-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_patient_details_ap_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient_details",
            name="booked_date",
            field=models.DateField(null=True),
        ),
    ]
