# Generated by Django 4.1.9 on 2023-05-24 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_remove_whatsappmessage_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
