# Generated by Django 4.1.9 on 2023-05-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_whatsappmessage_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="department",
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="doctor",
            field=models.CharField(default=True, max_length=100),
        ),
    ]
