# Generated by Django 4.1.9 on 2023-05-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_patient_department_patient_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
