# Generated by Django 4.1.9 on 2023-06-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_patient_pid"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="pid",),
    ]
