# Generated by Django 4.1.9 on 2023-06-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0015_department"),
    ]

    operations = [
        migrations.RenameModel(old_name="department", new_name="department_list",),
    ]
