# Generated by Django 4.1.9 on 2023-06-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0016_rename_department_department_list"),
    ]

    operations = [
        migrations.DeleteModel(name="Patient",),
    ]
