# Generated by Django 4.1.9 on 2023-07-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flaskapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule", old_name="date", new_name="scheduledate",
        ),
    ]
