# Generated by Django 4.1.9 on 2023-06-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history", old_name="advise", new_name="advice",
        ),
    ]
