# Generated by Django 4.1.9 on 2023-06-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_patient_details_ap_date_and_more"),
        ("doctor", "0003_history_patient_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="patient_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.patient_details",
            ),
        ),
    ]
