# Generated by Django 4.1.9 on 2023-06-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_alter_history_patient_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="history", name="patient_id",),
    ]
