# Generated by Django 4.1.7 on 2023-07-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_patient_details_ap_date_and_more'),
        ('doctor', '0006_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(max_length=200)),
                ('tests', models.TextField(max_length=200)),
                ('advice', models.TextField(max_length=200)),
                ('medicine', models.TextField(max_length=200)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient_details')),
            ],
        ),
    ]
