# Generated by Django 4.1.7 on 2023-07-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
