# Generated by Django 4.1.7 on 2023-07-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctorschedule_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
