# Generated by Django 4.1.7 on 2023-07-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_patient_details_ap_date_and_more'),
        ('doctor', '0011_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_date', to='doctor.doctorschedule')),
                ('appointment_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_time', to='doctor.doctorschedule')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient_details')),
            ],
        ),
    ]
