# Generated by Django 4.1.9 on 2023-07-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_patient_details_ap_date_and_more"),
        ("doctor", "0012_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorschedule",
            name="dep",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_schedules",
                to="accounts.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="doctorschedule",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_schedules",
                to="accounts.doctor",
            ),
        ),
    ]
