# Generated by Django 4.1.9 on 2023-07-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0013_doctorschedule_dep_alter_doctorschedule_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorschedule",
            name="on_leave",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
