# Generated by Django 4.1.9 on 2023-07-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_patient_details_ap_date_and_more"),
        ("doctor", "0014_alter_doctorschedule_on_leave"),
    ]

    operations = [
        migrations.RemoveField(model_name="appointment", name="appointment_time",),
        migrations.AddField(
            model_name="appointment",
            name="dept",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_appointment",
                to="accounts.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_appointment",
                to="accounts.doctor",
            ),
        ),
    ]
