# Generated by Django 4.1.9 on 2023-07-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "doctor",
            "0015_remove_appointment_appointment_time_appointment_dept_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorschedule",
            name="limit",
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
