# Generated by Django 4.1.9 on 2023-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0016_doctorschedule_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorschedule",
            name="appointment_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
